# railway.toml
[build]
  builder = "dockerfile"

[deploy]
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 3
  
[autoscale]
  min = 1
  max = 3
  cpuThreshold = 80
  memoryThreshold = 80